include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.graphql.dart'

  errors:
    invalid_annotation_target: ignore
